version: '2'
networks:
   bridge:

services:  

  ca:
    image: hyperledger/fabric-ca:latest
    ports:
      - 7054:7054    
    container_name: ca
    command: fabric-ca-server start -b admin:adminpw -d
  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LEDGERTYPE=ram
      - ORDERER_GENERAL_BATCHTIMEOUT=10s
      - ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT=10
      - ORDERER_GENERAL_MAXWINDOWSIZE=1000
      - ORDERER_GENERAL_ORDERERTYPE=solo
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_RAMLEDGER_HISTORY_SIZE=100    
    command: orderer
    ports:
      - 7050:7050
    networks:
      - bridge

  peer0:
    container_name: peer0
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=peer0
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ID=peer0
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_IGNORESECURITY=true    
    ports:
      - 7051:7051
      - 7053:7053
    links:
      - orderer:orderer
    volumes:
        - /var/run/:/host/var/run/        
    networks:
      - bridge

  # peer1:
  #   container_name: peer1
  #   image: con-fabric-peer:latest
  #   environment:
  #     - CORE_PEER_ADDRESSAUTODETECT=true
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - CORE_LOGGING_LEVEL=DEBUG
  #     - CORE_PEER_NETWORKID=peer1
  #     - CORE_NEXT=true
  #     - CORE_PEER_ENDORSER_ENABLED=true
  #     - CORE_PEER_ID=peer1
  #     - CORE_PEER_PROFILE_ENABLED=true
  #     - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
  #     - CORE_PEER_GOSSIP_ORGLEADER=true
  #     - CORE_PEER_GOSSIP_IGNORESECURITY=true    
  #   ports:
  #     - 7055:7051    
  #   links:
  #     - orderer:orderer
  #     - peer0:peer0
  #   volumes:
  #       - /var/run/:/host/var/run/        
  #   networks:
  #     - bridge

  # peer2:
  #   container_name: peer2
  #   image: con-fabric-peer:latest
  #   environment:
  #     - CORE_PEER_ADDRESSAUTODETECT=true
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - CORE_LOGGING_LEVEL=DEBUG
  #     - CORE_PEER_NETWORKID=peer2
  #     - CORE_NEXT=true
  #     - CORE_PEER_ENDORSER_ENABLED=true
  #     - CORE_PEER_ID=peer2
  #     - CORE_PEER_PROFILE_ENABLED=true
  #     - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
  #     - CORE_PEER_GOSSIP_ORGLEADER=true
  #     - CORE_PEER_GOSSIP_IGNORESECURITY=true
  #   ports:
  #     - 7056:7051    
  #   links:
  #     - orderer:orderer
  #     - peer0:peer0
  #     - peer1:peer1
  #   volumes:
  #       - /var/run/:/host/var/run/        
  #   networks:
  #     - bridge  